name: Pull-subtrees

on:
  push:
  pull_request:
  schedule:
    - cron:  '30 10 * * 0-6'

jobs:
  pull-subtrees:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
          fetch-depth: 0
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: julia-actions/setup-julia@v1
      with:
        version: 1.3
      env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Set up Git
      run: |
        git config --local user.email ${GITHUB_ACTOR}
        git config --local user.name "Tillmann Mühlpfordt @ GH Actions"

    - name: Call the julia script
      run: julia -e 'using Pkg; Pkg.add("JSON"); include("pull-subtrees.jl")'
